// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodCalcHub.ApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250304221738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("FoodCalcHub.ApiService.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prio")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReceptId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("FoodCalcHub.ApiService.Entities.Recept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recepts");
                });

            modelBuilder.Entity("FoodCalcHub.ApiService.Entities.Ingredient", b =>
                {
                    b.HasOne("FoodCalcHub.ApiService.Entities.Recept", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("ReceptId");
                });

            modelBuilder.Entity("FoodCalcHub.ApiService.Entities.Recept", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
