// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodHub.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250311211811_NewRecept")]
    partial class NewRecept
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodHub.Persistence.Configuration.IngredientAmountTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IngredientAmountTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Liter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Milliliter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Piece"
                        });
                });

            modelBuilder.Entity("FoodHub.Persistence.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("FoodHub.Persistence.Entities.Recept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recepts");
                });

            modelBuilder.Entity("FoodHub.Persistence.Entities.ReceptIngredient", b =>
                {
                    b.Property<Guid>("ReceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IngredientAmount")
                        .HasColumnType("int");

                    b.HasKey("ReceptId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ReceptIngredients", t =>
                        {
                            t.HasCheckConstraint("CK_ReceptIngredient_Amount", "Amount > 0");

                            t.HasCheckConstraint("CK_ReceptIngredient_IngredientAmount", "IngredientAmount > 0");
                        });
                });

            modelBuilder.Entity("FoodHub.Persistence.Entities.ReceptIngredient", b =>
                {
                    b.HasOne("FoodHub.Persistence.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodHub.Persistence.Entities.Recept", "Recept")
                        .WithMany("Ingredients")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("FoodHub.Persistence.Entities.Recept", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
